name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3-beta
    - name: Build with Gradle
      run: ./gradlew build
    - name: upload Spigot Plugin
      uses: actions/upload-artifact@v3
      with:
         name: Guilds
         path: build/libs
